version: '3.9'

services:
  backend:
    container_name: backend
    build: ./Backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - driverbridge

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - driverbridge

networks:
  driverbridge:
    driver: bridge

volumes:
  node_modules:  